/* generated by gbalua from main.lua - edit the .lua, not this file */
#include "gba_api.h"

static void lcl__init(void);
static void lcl__update(void);
static void lcl__draw(void);

static void lcl__init(void)
{
    gba_map_show(0);
}

static void lcl__update(void)
{
    if (gba_btnp(4, 0)) {
        gba_anim_reset(2);
    }
}

static void lcl__draw(void)
{
    gba_print("anim helpers", 8, 6, 7);
    gba_print("loop", 40, 40, 6);
    gba_print("pong", 108, 40, 6);
    gba_print("once", 176, 40, 6);
    gba_print("press a", 84, 130, 5);
    gba_spr(gba_anim(0, 0, 3, 655360L), 40, 60, 2, 2, 0 | (0 << 1));
    gba_spr(gba_anim_pingpong(1, 0, 3, 524288L), 108, 60, 2, 2, 0 | (0 << 1));
    gba_spr(gba_anim_once(2, 0, 3, 393216L), 176, 60, 2, 2, 0 | (0 << 1));
    if ((gba_anim_done(2) != 0)) {
        gba_print("done", 176, 90, 11);
    }
}

int main(void)
{
    gba_init();
    lcl__init();
    for (;;) {
        gba_vsync();
        lcl__update();
        lcl__draw();
        gba_endframe();
    }
    return 0;
}
