/* generated by gbalua from main.lua - edit the .lua, not this file */
#include "gba_api.h"

static void lcl__init(void);
static void lcl__update(void);
static void lcl__draw(void);

int lcl_t = 0;
int lcl_sx[6];
int lcl_sy[6];
int lcl_vx[6];
int lcl_vy[6];

static void lcl__init(void)
{
    gba_music(0, 1);
    { unsigned char lcl_i = 1; unsigned char L_lim0 = 6;
        for (; lcl_i <= L_lim0; ++lcl_i) {
            lcl_sx[lcl_i - 1] = (20 + (((lcl_i) << 6) - ((lcl_i) << 5) - ((lcl_i) << 1)));
            lcl_sy[lcl_i - 1] = (40 + (((((lcl_i) << 4) + (lcl_i))) % (80)));
            lcl_vx[lcl_i - 1] = (((((lcl_i & 1)) << 2)) - 2);
            lcl_vy[lcl_i - 1] = (((lcl_i) % (3)) - 1);
            if (((lcl_vx - 1)[lcl_i] == 0)) {
                lcl_vx[lcl_i - 1] = 2;
            }
            if (((lcl_vy - 1)[lcl_i] == 0)) {
                lcl_vy[lcl_i - 1] = 1;
            }
        }
    }
}

static void lcl__update(void)
{
    lcl_t = (lcl_t + 1);
    { unsigned char lcl_i = 1; unsigned char L_lim1 = 6;
        for (; lcl_i <= L_lim1; ++lcl_i) {
            lcl_sx[lcl_i - 1] = ((lcl_sx - 1)[lcl_i] + (lcl_vx - 1)[lcl_i]);
            lcl_sy[lcl_i - 1] = ((lcl_sy - 1)[lcl_i] + (lcl_vy - 1)[lcl_i]);
            if ((((lcl_sx - 1)[lcl_i] < 4) || ((lcl_sx - 1)[lcl_i] > 220))) {
                lcl_vx[lcl_i - 1] = (-(lcl_vx - 1)[lcl_i]);
            }
            if ((((lcl_sy - 1)[lcl_i] < 4) || ((lcl_sy - 1)[lcl_i] > 140))) {
                lcl_vy[lcl_i - 1] = (-(lcl_vy - 1)[lcl_i]);
            }
        }
    }
    if (gba_btn(4, 0)) {
        gba_blend(4, 29491L /* 0.45 */);
    } else {
        { int lcl_phase = ((lcl_t) % (120));
            if ((lcl_phase < 60)) {
                { long lcl_a = (long)((((long long)(((long)lcl_phase << 16))) << 16) / (3932160L));
                    if ((lcl_a > 32768L /* 0.5 */)) {
                        lcl_a = (65536L - lcl_a);
                    }
                    gba_fade((lcl_a << 1), 0);
                }
            } else {
                { int lcl_p = (lcl_phase - 60);
                    { long lcl_a = (long)((((long long)(((long)lcl_p << 16))) << 16) / (3932160L));
                        if ((lcl_a > 32768L /* 0.5 */)) {
                            lcl_a = (65536L - lcl_a);
                        }
                        gba_fade((lcl_a << 1), ((1) ? 1 : 0));
                    }
                }
            }
        }
    }
}

static void lcl__draw(void)
{
    gba_cls(1);
    gba_rectfill(0, 0, 239, 26, 3);
    gba_rectfill(0, 130, 239, 159, 8);
    gba_circfill(120, 80, 30, 12);
    gba_print("effects: fade + blend", 8, 4, 7);
    gba_print("hold a: ghost", 8, 148, 7);
    { unsigned char lcl_i = 1; unsigned char L_lim2 = 6;
        for (; lcl_i <= L_lim2; ++lcl_i) {
            gba_spr(0, (lcl_sx - 1)[lcl_i], (lcl_sy - 1)[lcl_i], 2, 2, 0 | (0 << 1));
        }
    }
}

int main(void)
{
    gba_init();
    lcl__init();
    for (;;) {
        gba_vsync();
        lcl__update();
        lcl__draw();
        gba_endframe();
    }
    return 0;
}
