/* generated by gbalua from main.lua - edit the .lua, not this file */
#include "gba_api.h"

static void gtl__init(void);
static void gtl__update(void);
static void gtl__draw(void);

int gtl_t = 0;
int gtl_sx[6];
int gtl_sy[6];
int gtl_vx[6];
int gtl_vy[6];

static void gtl__init(void)
{
    gba_music(0, 1);
    { unsigned char gtl_i = 1; unsigned char L_lim0 = 6;
        for (; gtl_i <= L_lim0; ++gtl_i) {
            gtl_sx[gtl_i - 1] = (20 + (((gtl_i) << 6) - ((gtl_i) << 5) - ((gtl_i) << 1)));
            gtl_sy[gtl_i - 1] = (40 + (((((gtl_i) << 4) + (gtl_i))) % (80)));
            gtl_vx[gtl_i - 1] = (((((gtl_i & 1)) << 2)) - 2);
            gtl_vy[gtl_i - 1] = (((gtl_i) % (3)) - 1);
            if (((gtl_vx - 1)[gtl_i] == 0)) {
                gtl_vx[gtl_i - 1] = 2;
            }
            if (((gtl_vy - 1)[gtl_i] == 0)) {
                gtl_vy[gtl_i - 1] = 1;
            }
        }
    }
}

static void gtl__update(void)
{
    gtl_t = (gtl_t + 1);
    { unsigned char gtl_i = 1; unsigned char L_lim1 = 6;
        for (; gtl_i <= L_lim1; ++gtl_i) {
            gtl_sx[gtl_i - 1] = ((gtl_sx - 1)[gtl_i] + (gtl_vx - 1)[gtl_i]);
            gtl_sy[gtl_i - 1] = ((gtl_sy - 1)[gtl_i] + (gtl_vy - 1)[gtl_i]);
            if ((((gtl_sx - 1)[gtl_i] < 4) || ((gtl_sx - 1)[gtl_i] > 220))) {
                gtl_vx[gtl_i - 1] = (-(gtl_vx - 1)[gtl_i]);
            }
            if ((((gtl_sy - 1)[gtl_i] < 4) || ((gtl_sy - 1)[gtl_i] > 140))) {
                gtl_vy[gtl_i - 1] = (-(gtl_vy - 1)[gtl_i]);
            }
        }
    }
    if (gba_btn(4, 0)) {
        gba_blend(4, 29491L /* 0.45 */);
    } else {
        { int gtl_phase = ((gtl_t) % (120));
            if ((gtl_phase < 60)) {
                { long gtl_a = (long)((((long long)(((long)gtl_phase << 16))) << 16) / (3932160L));
                    if ((gtl_a > 32768L /* 0.5 */)) {
                        gtl_a = (65536L - gtl_a);
                    }
                    gba_fade((gtl_a << 1), 0);
                }
            } else {
                { int gtl_p = (gtl_phase - 60);
                    { long gtl_a = (long)((((long long)(((long)gtl_p << 16))) << 16) / (3932160L));
                        if ((gtl_a > 32768L /* 0.5 */)) {
                            gtl_a = (65536L - gtl_a);
                        }
                        gba_fade((gtl_a << 1), ((1) ? 1 : 0));
                    }
                }
            }
        }
    }
}

static void gtl__draw(void)
{
    gba_cls(1);
    gba_rectfill(0, 0, 239, 26, 3);
    gba_rectfill(0, 130, 239, 159, 8);
    gba_circfill(120, 80, 30, 12);
    gba_print("effects: fade + blend", 8, 4, 7);
    gba_print("hold a: ghost", 8, 148, 7);
    { unsigned char gtl_i = 1; unsigned char L_lim2 = 6;
        for (; gtl_i <= L_lim2; ++gtl_i) {
            gba_spr(0, (gtl_sx - 1)[gtl_i], (gtl_sy - 1)[gtl_i], 2, 2, 0 | (0 << 1));
        }
    }
}

int main(void)
{
    gba_init();
    gtl__init();
    for (;;) {
        gba_vsync();
        gtl__update();
        gtl__draw();
        gba_endframe();
    }
    return 0;
}
