/* generated by gbalua from main.lua - edit the .lua, not this file */
#include "gba_api.h"

static void lcl__update60(void);
static void lcl__draw(void);

int lcl_x = 112;
int lcl_y = 72;

static void lcl__update60(void)
{
    if (gba_btn(1, 0)) {
        lcl_x = (lcl_x + 2);
    }
    if (gba_btn(0, 0)) {
        lcl_x = (lcl_x - 2);
    }
    if (gba_btn(3, 0)) {
        lcl_y = (lcl_y + 2);
    }
    if (gba_btn(2, 0)) {
        lcl_y = (lcl_y - 2);
    }
}

static void lcl__draw(void)
{
    gba_cls(1);
    gba_print("hello gba", 88, 24, 14);
    gba_spr(0, lcl_x, lcl_y, 2, 2, 0 | (0 << 1));
}

int main(void)
{
    gba_init();
    for (;;) {
        gba_vsync();
        lcl__update60();
        lcl__draw();
        gba_endframe();
    }
    return 0;
}
