/* generated by gbalua from main.lua - edit the .lua, not this file */
#include "gba_api.h"

static void gtl__init(void);
static void gtl__update(void);
static void gtl__draw(void);

int gtl_sky[160];
unsigned char gtl_st[8];
int gtl_hi = 0;
int gtl_lastticks = 0;
int gtl_frames = 0;

static void gtl__init(void)
{
    { unsigned char gtl_y = 0; unsigned char L_lim0 = 159;
        for (; gtl_y <= L_lim0; ++gtl_y) {
            { int gtl_b = (int)((524288L + ((long)gtl_y << 13)) >> 16);
                if ((gtl_b > 31)) {
                    gtl_b = 31;
                }
                gtl_sky[gtl_y - 1] = (gtl_b * 1024);
            }
        }
    }
    gba_hgradient(gtl_sky);
    if ((gba_load(0, gtl_st, 8) > 0)) {
        gtl_hi = (gtl_st[0] + (gtl_st[1] * 256));
    } else {
        gtl_hi = 0;
    }
}

static void gtl__update(void)
{
    gtl_frames = (gtl_frames + 1);
    gba_timer_start();
    { int gtl_s = 0;
        { int gtl_i = 0; int L_lim1 = 3999;
            for (; gtl_i <= L_lim1; ++gtl_i) {
                gtl_s = (gtl_s + (((gtl_i) << 1) + (gtl_i)));
            }
        }
        gtl_lastticks = gba_timer_read();
        if ((((gtl_frames) % (60)) == 0)) {
            gtl_hi = (gtl_hi + 1);
            gtl_st[0] = (gtl_hi & 255);
            gtl_st[1] = ((gtl_hi >> 8) & 255);
            gba_save(0, gtl_st, 8);
        }
        if ((gtl_frames > 300)) {
            gba_run();
        }
    }
}

static void gtl__draw(void)
{
    gba_cls(0);
    gba_print("hwtest", 8, 8, 7);
    gba_print("hi", 8, 20, 11);
    gba_print_int(gtl_hi, 40, 20, 11);
    gba_print("f", 8, 32, 6);
    gba_print_int(gtl_frames, 40, 32, 6);
    gba_print("t", 8, 44, 9);
    gba_print_int(gtl_lastticks, 40, 44, 9);
}

int main(void)
{
    gba_init();
    gtl__init();
    for (;;) {
        gba_vsync();
        gtl__update();
        gtl__draw();
        gba_endframe();
    }
    return 0;
}
