/* generated by gbalua from main.lua - edit the .lua, not this file */
#include "gba_api.h"

static void gtl__draw(void);

static void gtl__draw(void)
{
    gba_cls(1);
    gba_print("hello gba", 100, 24, 14);
    gba_circfill(120, 92, 38, 10);
    gba_rectfill(106, 76, 113, 86, 0);
    gba_rectfill(127, 76, 134, 86, 0);
    gba_circfill(120, 104, 11, 0);
}

int main(void)
{
    gba_init();
    for (;;) {
        gba_vsync();
        gtl__draw();
        gba_endframe();
    }
    return 0;
}
