/* generated by gbalua from main.lua - edit the .lua, not this file */
#include "gba_api.h"

static void lcl__init(void);
static void lcl__update(void);
static void lcl__draw(void);

int lcl_sky[160];
unsigned char lcl_st[8];
int lcl_hi = 0;
int lcl_lastticks = 0;
int lcl_frames = 0;

static void lcl__init(void)
{
    { unsigned char lcl_y = 0; unsigned char L_lim0 = 159;
        for (; lcl_y <= L_lim0; ++lcl_y) {
            { int lcl_b = (int)((524288L + ((long)lcl_y << 13)) >> 16);
                if ((lcl_b > 31)) {
                    lcl_b = 31;
                }
                lcl_sky[lcl_y - 1] = (lcl_b * 1024);
            }
        }
    }
    gba_hgradient(lcl_sky);
    if ((gba_load(0, lcl_st, 8) > 0)) {
        lcl_hi = (lcl_st[0] + (lcl_st[1] * 256));
    } else {
        lcl_hi = 0;
    }
}

static void lcl__update(void)
{
    lcl_frames = (lcl_frames + 1);
    gba_timer_start();
    { int lcl_s = 0;
        { int lcl_i = 0; int L_lim1 = 3999;
            for (; lcl_i <= L_lim1; ++lcl_i) {
                lcl_s = (lcl_s + (((lcl_i) << 1) + (lcl_i)));
            }
        }
        lcl_lastticks = gba_timer_read();
        if ((((lcl_frames) % (60)) == 0)) {
            lcl_hi = (lcl_hi + 1);
            lcl_st[0] = (lcl_hi & 255);
            lcl_st[1] = ((lcl_hi >> 8) & 255);
            gba_save(0, lcl_st, 8);
        }
        if ((lcl_frames > 300)) {
            gba_run();
        }
    }
}

static void lcl__draw(void)
{
    gba_cls(0);
    gba_print("hwtest", 8, 8, 7);
    gba_print("hi", 8, 20, 11);
    gba_print_int(lcl_hi, 40, 20, 11);
    gba_print("f", 8, 32, 6);
    gba_print_int(lcl_frames, 40, 32, 6);
    gba_print("t", 8, 44, 9);
    gba_print_int(lcl_lastticks, 40, 44, 9);
}

int main(void)
{
    gba_init();
    lcl__init();
    for (;;) {
        gba_vsync();
        lcl__update();
        lcl__draw();
        gba_endframe();
    }
    return 0;
}
