/* generated by gbalua from main.lua - edit the .lua, not this file */
#include "gba_api.h"

static void gtl__init(void);
static void gtl__update(void);
static void gtl__draw(void);

long gtl_cx = 8388608L; /* 128 */
long gtl_cy = 8388608L; /* 128 */
long gtl_ang = 0L; /* 0 */
long gtl_zoom = 65536L; /* 1 */

static void gtl__init(void)
{
    gba_mode7();
}

static void gtl__update(void)
{
    if (gba_btn(0, 0)) {
        gtl_ang = (gtl_ang - 328L /* 0.005 */);
    }
    if (gba_btn(1, 0)) {
        gtl_ang = (gtl_ang + 328L /* 0.005 */);
    }
    if ((gtl_ang < 0L)) {
        gtl_ang = (gtl_ang + 65536L);
    }
    if ((gtl_ang > 65536L)) {
        gtl_ang = (gtl_ang - 65536L);
    }
    { int gtl_spd = 0;
        if (gba_btn(2, 0)) {
            gtl_spd = 3;
        }
        if (gba_btn(3, 0)) {
            gtl_spd = (-3);
        }
        if ((gtl_spd != 0)) {
            gtl_cx = (gtl_cx + (gba_fcos(gtl_ang) * gtl_spd));
            gtl_cy = (gtl_cy + (gba_fsin(gtl_ang) * gtl_spd));
        }
        if (gba_btn(4, 0)) {
            gtl_zoom = (gtl_zoom + 1966L /* 0.03 */);
        }
        if (gba_btn(5, 0)) {
            gtl_zoom = (gtl_zoom - 1966L /* 0.03 */);
        }
        if ((gtl_zoom < 16384L /* 0.25 */)) {
            gtl_zoom = 16384L /* 0.25 */;
        }
        if ((gtl_zoom > 262144L)) {
            gtl_zoom = 262144L;
        }
        gba_mode7_cam(gtl_cx, gtl_cy, gtl_ang, gtl_zoom);
    }
}

static void gtl__draw(void)
{
    gba_print("mode7", 8, 8, 7);
    gba_print("dpad+ab", 8, 20, 7);
}

int main(void)
{
    gba_init();
    gtl__init();
    for (;;) {
        gba_vsync();
        gtl__update();
        gtl__draw();
        gba_endframe();
    }
    return 0;
}
