/* generated by gbalua from main.lua - edit the .lua, not this file */
#include "gba_api.h"

static void lcl__init(void);
static void lcl__update(void);
static void lcl__draw(void);

long lcl_cx = 8388608L; /* 128 */
long lcl_cy = 8388608L; /* 128 */
long lcl_ang = 0L; /* 0 */
long lcl_zoom = 65536L; /* 1 */

static void lcl__init(void)
{
    gba_mode7();
}

static void lcl__update(void)
{
    if (gba_btn(0, 0)) {
        lcl_ang = (lcl_ang - 328L /* 0.005 */);
    }
    if (gba_btn(1, 0)) {
        lcl_ang = (lcl_ang + 328L /* 0.005 */);
    }
    if ((lcl_ang < 0L)) {
        lcl_ang = (lcl_ang + 65536L);
    }
    if ((lcl_ang > 65536L)) {
        lcl_ang = (lcl_ang - 65536L);
    }
    { int lcl_spd = 0;
        if (gba_btn(2, 0)) {
            lcl_spd = 3;
        }
        if (gba_btn(3, 0)) {
            lcl_spd = (-3);
        }
        if ((lcl_spd != 0)) {
            lcl_cx = (lcl_cx + (gba_fcos(lcl_ang) * lcl_spd));
            lcl_cy = (lcl_cy + (gba_fsin(lcl_ang) * lcl_spd));
        }
        if (gba_btn(4, 0)) {
            lcl_zoom = (lcl_zoom + 1966L /* 0.03 */);
        }
        if (gba_btn(5, 0)) {
            lcl_zoom = (lcl_zoom - 1966L /* 0.03 */);
        }
        if ((lcl_zoom < 16384L /* 0.25 */)) {
            lcl_zoom = 16384L /* 0.25 */;
        }
        if ((lcl_zoom > 262144L)) {
            lcl_zoom = 262144L;
        }
        gba_mode7_cam(lcl_cx, lcl_cy, lcl_ang, lcl_zoom);
    }
}

static void lcl__draw(void)
{
    gba_print("mode7", 8, 8, 7);
    gba_print("dpad+ab", 8, 20, 7);
}

int main(void)
{
    gba_init();
    lcl__init();
    for (;;) {
        gba_vsync();
        lcl__update();
        lcl__draw();
        gba_endframe();
    }
    return 0;
}
