/* generated by gbalua from main.lua - edit the .lua, not this file */
#include "gba_api.h"

static void lcl__init(void);
static void lcl__update60(void);
static void lcl_next_scene(void);
static void lcl_changed(void);
static void lcl__draw(void);
static void lcl_hud(void);
static void lcl_s_shapes(void);
static void lcl_s_sprites(void);
static void lcl_s_effects(void);
static void lcl_s_mode7(void);
static void lcl_s_abg(void);
static void lcl_s_plasma(void);
static void lcl_reset_display(void);

int lcl_scene = 0;
int lcl_nscenes = 6;
int lcl_t2 = 0;
int lcl_plasma_started = 0;
int lcl_abg_started = 0;
int lcl_m7_started = 0;
int lcl_last_switch = 0;
unsigned char lcl_tiles[128];
unsigned char lcl_amap[256];
int lcl_apal[256];

static void lcl__init(void)
{
    { unsigned char lcl_i = 1; unsigned char L_lim0 = 64;
        for (; lcl_i <= L_lim0; ++lcl_i) {
            (lcl_tiles - 1)[lcl_i] = 1;
        }
    }
    { unsigned char lcl_i = 65; unsigned char L_lim1 = 128;
        for (; lcl_i <= L_lim1; ++lcl_i) {
            (lcl_tiles - 1)[lcl_i] = 2;
        }
    }
    lcl_apal[1] = gba_rgb15(255, 70, 70);
    lcl_apal[2] = gba_rgb15(70, 130, 255);
    { unsigned char lcl_r = 0; unsigned char L_lim2 = 15;
        for (; lcl_r <= L_lim2; ++lcl_r) {
            { unsigned char lcl_c = 0; unsigned char L_lim3 = 15;
                for (; lcl_c <= L_lim3; ++lcl_c) {
                    lcl_amap[((((lcl_r) << 4)) + lcl_c)] = ((lcl_r + lcl_c) & 1);
                }
            }
        }
    }
}

static void lcl__update60(void)
{
    lcl_t2 = (lcl_t2 + 1);
    if (((gba_realframes() - lcl_last_switch) > 240)) {
        lcl_next_scene();
    }
    if (gba_btnp(6, 0)) {
        lcl_scene = ((((lcl_scene + lcl_nscenes) - 1)) % (lcl_nscenes));
        lcl_changed();
    }
    if (gba_btnp(7, 0)) {
        lcl_next_scene();
    }
}

static void lcl_next_scene(void)
{
    lcl_scene = (((lcl_scene + 1)) % (lcl_nscenes));
    lcl_changed();
}

static void lcl_changed(void)
{
    lcl_last_switch = gba_realframes();
    lcl_m7_started = 0;
    lcl_abg_started = 0;
    lcl_plasma_started = 0;
}

static void lcl__draw(void)
{
    if ((lcl_scene == 0)) {
        lcl_s_shapes();
    } else if ((lcl_scene == 1)) {
        lcl_s_sprites();
    } else if ((lcl_scene == 2)) {
        lcl_s_effects();
    } else if ((lcl_scene == 3)) {
        lcl_s_mode7();
    } else if ((lcl_scene == 4)) {
        lcl_s_abg();
    } else if ((lcl_scene == 5)) {
        lcl_s_plasma();
    }
    lcl_hud();
}

static void lcl_hud(void)
{
    if ((lcl_scene == 5)) {
        return;
    }
    gba_print("L/R:", 4, 4, 6);
    gba_print_int(lcl_scene, 34, 4, 10);
}

static void lcl_s_shapes(void)
{
    lcl_reset_display();
    gba_cls(1);
    gba_circfill(48, 88, 20, 8);
    gba_circ(48, 88, 26, 10);
    gba_rectfill(88, 68, 140, 108, 12);
    gba_rect(88, 68, 140, 108, 7);
    gba_line(16, 30, 224, 40, 11);
    gba_clip(150, 58, 60, 60);
    { unsigned char lcl_i = 0; unsigned char L_lim4 = 30;
        for (; lcl_i <= L_lim4; ++lcl_i) {
            gba_circ(180, 88, (((lcl_i) << 1)), 9);
        }
    }
    gba_clip(-1, -1, -1, -1);
    gba_rect(150, 58, 209, 117, 14);
    gba_print("shapes+clip+fade", 60, 140, 7);
    { long lcl_f = (long)((((long long)((gba_fsin((long)((((long long)(((long)lcl_t2 << 16))) << 16) / (8519680L))) + 65536L))) << 16) / (327680L));
        gba_fade(lcl_f, ((0) ? 1 : 0));
    }
}

static void lcl_s_sprites(void)
{
    lcl_reset_display();
    gba_cls(0);
    gba_print("affine sprites", 66, 140, 7);
    { long lcl_ang = (long)((((long long)(((long)lcl_t2 << 16))) << 16) / (13107200L));
        { long lcl_sc = (65536L + (long)(((long long)(gba_fsin((long)((((long long)(((long)lcl_t2 << 16))) << 16) / (5898240L)))) * (32768L /* 0.5 */)) >> 16));
            gba_sprr(0, 70, 74, lcl_ang, lcl_sc);
            gba_sprr2(0, 170, 74, (-lcl_ang), (65536L + (long)(((long long)(gba_fsin((long)((((long long)(((long)lcl_t2 << 16))) << 16) / (3932160L)))) * (39322L /* 0.6 */)) >> 16)), (65536L - (long)(((long long)(gba_fsin((long)((((long long)(((long)lcl_t2 << 16))) << 16) / (3932160L)))) * (26214L /* 0.4 */)) >> 16)));
            gba_mosaic((int)(((gba_fsin((long)((((long long)(((long)lcl_t2 << 16))) << 16) / (6553600L))) + 65536L) << 2) >> 16));
            gba_spr_mosaic(((1) ? 1 : 0));
            gba_spr(0, 112, 60, 2, 2, 0 | (0 << 1));
            gba_spr_mosaic(((0) ? 1 : 0));
            gba_mosaic(0);
        }
    }
}

static void lcl_s_effects(void)
{
    lcl_reset_display();
    gba_cls(2);
    gba_circfill(120, 80, 50, 12);
    gba_rectfill(40, 50, 90, 110, 8);
    gba_rectfill(150, 50, 200, 110, 11);
    gba_print("blend + fade", 72, 140, 7);
    gba_spr_blend();
    gba_sprr(0, (int)((5242880L + (gba_fsin((long)((((long long)(((long)lcl_t2 << 16))) << 16) / (4587520L))) * 40)) >> 16), 80, (long)((((long long)(((long)lcl_t2 << 16))) << 16) / (19660800L)), 98304L /* 1.5 */);
    gba_spr_blend();
    gba_sprr(0, (int)((10485760L + (gba_fcos((long)((((long long)(((long)lcl_t2 << 16))) << 16) / (4587520L))) * 40)) >> 16), 80, (long)((((long long)(((long)(-lcl_t2) << 16))) << 16) / (19660800L)), 98304L /* 1.5 */);
    gba_spr_blend_off();
    { long lcl_s = gba_fsin((long)((((long long)(((long)lcl_t2 << 16))) << 16) / (2621440L)));
        { long lcl_f = 0L;
            if ((lcl_s > 45875L /* 0.7 */)) {
                lcl_f = (lcl_s - 45875L /* 0.7 */);
            }
            gba_fade(lcl_f, ((1) ? 1 : 0));
        }
    }
}

static void lcl_s_mode7(void)
{
    if ((lcl_m7_started == 0)) {
        gba_blend_off();
        if ((lcl_abg_started == 1)) {
            gba_abg_off();
            lcl_abg_started = 0;
        }
        gba_mode7();
        lcl_m7_started = 1;
    }
    gba_mode7_cam(((long)(((lcl_t2) << 1)) << 16), ((long)lcl_t2 << 16), (long)((((long long)(((long)lcl_t2 << 16))) << 16) / (26214400L)), (65536L + (long)(((long long)(gba_fsin((long)((((long long)(((long)lcl_t2 << 16))) << 16) / (7864320L)))) * (26214L /* 0.4 */)) >> 16)));
}

static void lcl_s_abg(void)
{
    if ((lcl_abg_started == 0)) {
        gba_blend_off();
        gba_mode7_off();
        gba_abg_setup(lcl_tiles, 2, lcl_amap, 16, lcl_apal);
        lcl_abg_started = 1;
    }
    gba_abg_cam(4194304L, 4194304L, (long)((((long long)(((long)lcl_t2 << 16))) << 16) / (19660800L)), (65536L + (long)(((long long)(gba_fsin((long)((((long long)(((long)lcl_t2 << 16))) << 16) / (6553600L)))) * (32768L /* 0.5 */)) >> 16)));
}

static void lcl_s_plasma(void)
{
    if ((lcl_plasma_started == 0)) {
        gba_blend_off();
        gba_mode7_off();
        gba_abg_off();
        gba_mode15();
        lcl_plasma_started = 1;
    }
    { int lcl_ph = (((lcl_t2) << 1) + (lcl_t2));
        { int lcl_y = 0;
            while ((lcl_y < 128)) {
                { int lcl_x = 0;
                    while ((lcl_x < 160)) {
                        { long lcl_r = (8388608L + (gba_fsin((long)((((long long)(((long)(lcl_x + lcl_ph) << 16))) << 16) / (2621440L))) * 127));
                            { long lcl_g = (8388608L + (gba_fsin((long)((((long long)(((long)(lcl_y - lcl_ph) << 16))) << 16) / (3276800L))) * 127));
                                { long lcl_b = (8388608L + (gba_fsin((long)((((long long)(((long)(lcl_x + lcl_y) << 16))) << 16) / (3932160L))) * 127));
                                    gba_fillrect15(lcl_x, lcl_y, 8, 8, gba_rgb15((int)(lcl_r >> 16), (int)(lcl_g >> 16), (int)(lcl_b >> 16)));
                                    lcl_x = (lcl_x + 8);
                                }
                            }
                        }
                    }
                    lcl_y = (lcl_y + 8);
                }
            }
            gba_flip15();
        }
    }
}

static void lcl_reset_display(void)
{
    gba_abg_off();
    gba_mode7_off();
    gba_blend_off();
}

int main(void)
{
    gba_init();
    lcl__init();
    for (;;) {
        gba_vsync();
        lcl__update60();
        lcl__draw();
        gba_endframe();
    }
    return 0;
}
