/* generated by gbalua from main.lua - edit the .lua, not this file */
#include "gba_api.h"

static void gtl__init(void);
static void gtl__update60(void);
static void gtl_next_scene(void);
static void gtl_changed(void);
static void gtl__draw(void);
static void gtl_hud(void);
static void gtl_s_shapes(void);
static void gtl_s_sprites(void);
static void gtl_s_effects(void);
static void gtl_s_mode7(void);
static void gtl_s_abg(void);
static void gtl_s_plasma(void);
static void gtl_reset_display(void);

int gtl_scene = 0;
int gtl_nscenes = 6;
int gtl_t2 = 0;
int gtl_plasma_started = 0;
int gtl_abg_started = 0;
int gtl_m7_started = 0;
int gtl_last_switch = 0;
unsigned char gtl_tiles[128];
unsigned char gtl_amap[256];
int gtl_apal[256];

static void gtl__init(void)
{
    { unsigned char gtl_i = 1; unsigned char L_lim0 = 64;
        for (; gtl_i <= L_lim0; ++gtl_i) {
            (gtl_tiles - 1)[gtl_i] = 1;
        }
    }
    { unsigned char gtl_i = 65; unsigned char L_lim1 = 128;
        for (; gtl_i <= L_lim1; ++gtl_i) {
            (gtl_tiles - 1)[gtl_i] = 2;
        }
    }
    gtl_apal[1] = gba_rgb15(255, 70, 70);
    gtl_apal[2] = gba_rgb15(70, 130, 255);
    { unsigned char gtl_r = 0; unsigned char L_lim2 = 15;
        for (; gtl_r <= L_lim2; ++gtl_r) {
            { unsigned char gtl_c = 0; unsigned char L_lim3 = 15;
                for (; gtl_c <= L_lim3; ++gtl_c) {
                    gtl_amap[((((gtl_r) << 4)) + gtl_c)] = ((gtl_r + gtl_c) & 1);
                }
            }
        }
    }
}

static void gtl__update60(void)
{
    gtl_t2 = (gtl_t2 + 1);
    if (((gba_realframes() - gtl_last_switch) > 240)) {
        gtl_next_scene();
    }
    if (gba_btnp(6, 0)) {
        gtl_scene = ((((gtl_scene + gtl_nscenes) - 1)) % (gtl_nscenes));
        gtl_changed();
    }
    if (gba_btnp(7, 0)) {
        gtl_next_scene();
    }
}

static void gtl_next_scene(void)
{
    gtl_scene = (((gtl_scene + 1)) % (gtl_nscenes));
    gtl_changed();
}

static void gtl_changed(void)
{
    gtl_last_switch = gba_realframes();
    gtl_m7_started = 0;
    gtl_abg_started = 0;
    gtl_plasma_started = 0;
}

static void gtl__draw(void)
{
    if ((gtl_scene == 0)) {
        gtl_s_shapes();
    } else if ((gtl_scene == 1)) {
        gtl_s_sprites();
    } else if ((gtl_scene == 2)) {
        gtl_s_effects();
    } else if ((gtl_scene == 3)) {
        gtl_s_mode7();
    } else if ((gtl_scene == 4)) {
        gtl_s_abg();
    } else if ((gtl_scene == 5)) {
        gtl_s_plasma();
    }
    gtl_hud();
}

static void gtl_hud(void)
{
    if ((gtl_scene == 5)) {
        return;
    }
    gba_print("L/R:", 4, 4, 6);
    gba_print_int(gtl_scene, 34, 4, 10);
}

static void gtl_s_shapes(void)
{
    gtl_reset_display();
    gba_cls(1);
    gba_circfill(48, 88, 20, 8);
    gba_circ(48, 88, 26, 10);
    gba_rectfill(88, 68, 140, 108, 12);
    gba_rect(88, 68, 140, 108, 7);
    gba_line(16, 30, 224, 40, 11);
    gba_clip(150, 58, 60, 60);
    { unsigned char gtl_i = 0; unsigned char L_lim4 = 30;
        for (; gtl_i <= L_lim4; ++gtl_i) {
            gba_circ(180, 88, (((gtl_i) << 1)), 9);
        }
    }
    gba_clip(-1, -1, -1, -1);
    gba_rect(150, 58, 209, 117, 14);
    gba_print("shapes+clip+fade", 60, 140, 7);
    { long gtl_f = (long)((((long long)((gba_fsin((long)((((long long)(((long)gtl_t2 << 16))) << 16) / (8519680L))) + 65536L))) << 16) / (327680L));
        gba_fade(gtl_f, ((0) ? 1 : 0));
    }
}

static void gtl_s_sprites(void)
{
    gtl_reset_display();
    gba_cls(0);
    gba_print("affine sprites", 66, 140, 7);
    { long gtl_ang = (long)((((long long)(((long)gtl_t2 << 16))) << 16) / (13107200L));
        { long gtl_sc = (65536L + (long)(((long long)(gba_fsin((long)((((long long)(((long)gtl_t2 << 16))) << 16) / (5898240L)))) * (32768L /* 0.5 */)) >> 16));
            gba_sprr(0, 70, 74, gtl_ang, gtl_sc);
            gba_sprr2(0, 170, 74, (-gtl_ang), (65536L + (long)(((long long)(gba_fsin((long)((((long long)(((long)gtl_t2 << 16))) << 16) / (3932160L)))) * (39322L /* 0.6 */)) >> 16)), (65536L - (long)(((long long)(gba_fsin((long)((((long long)(((long)gtl_t2 << 16))) << 16) / (3932160L)))) * (26214L /* 0.4 */)) >> 16)));
            gba_mosaic((int)(((gba_fsin((long)((((long long)(((long)gtl_t2 << 16))) << 16) / (6553600L))) + 65536L) << 2) >> 16));
            gba_spr_mosaic(((1) ? 1 : 0));
            gba_spr(0, 112, 60, 2, 2, 0 | (0 << 1));
            gba_spr_mosaic(((0) ? 1 : 0));
            gba_mosaic(0);
        }
    }
}

static void gtl_s_effects(void)
{
    gtl_reset_display();
    gba_cls(2);
    gba_circfill(120, 80, 50, 12);
    gba_rectfill(40, 50, 90, 110, 8);
    gba_rectfill(150, 50, 200, 110, 11);
    gba_print("blend + fade", 72, 140, 7);
    gba_spr_blend();
    gba_sprr(0, (int)((5242880L + (gba_fsin((long)((((long long)(((long)gtl_t2 << 16))) << 16) / (4587520L))) * 40)) >> 16), 80, (long)((((long long)(((long)gtl_t2 << 16))) << 16) / (19660800L)), 98304L /* 1.5 */);
    gba_spr_blend();
    gba_sprr(0, (int)((10485760L + (gba_fcos((long)((((long long)(((long)gtl_t2 << 16))) << 16) / (4587520L))) * 40)) >> 16), 80, (long)((((long long)(((long)(-gtl_t2) << 16))) << 16) / (19660800L)), 98304L /* 1.5 */);
    gba_spr_blend_off();
    { long gtl_s = gba_fsin((long)((((long long)(((long)gtl_t2 << 16))) << 16) / (2621440L)));
        { long gtl_f = 0L;
            if ((gtl_s > 45875L /* 0.7 */)) {
                gtl_f = (gtl_s - 45875L /* 0.7 */);
            }
            gba_fade(gtl_f, ((1) ? 1 : 0));
        }
    }
}

static void gtl_s_mode7(void)
{
    if ((gtl_m7_started == 0)) {
        gba_blend_off();
        if ((gtl_abg_started == 1)) {
            gba_abg_off();
            gtl_abg_started = 0;
        }
        gba_mode7();
        gtl_m7_started = 1;
    }
    gba_mode7_cam(((long)(((gtl_t2) << 1)) << 16), ((long)gtl_t2 << 16), (long)((((long long)(((long)gtl_t2 << 16))) << 16) / (26214400L)), (65536L + (long)(((long long)(gba_fsin((long)((((long long)(((long)gtl_t2 << 16))) << 16) / (7864320L)))) * (26214L /* 0.4 */)) >> 16)));
}

static void gtl_s_abg(void)
{
    if ((gtl_abg_started == 0)) {
        gba_blend_off();
        gba_mode7_off();
        gba_abg_setup(gtl_tiles, 2, gtl_amap, 16, gtl_apal);
        gtl_abg_started = 1;
    }
    gba_abg_cam(4194304L, 4194304L, (long)((((long long)(((long)gtl_t2 << 16))) << 16) / (19660800L)), (65536L + (long)(((long long)(gba_fsin((long)((((long long)(((long)gtl_t2 << 16))) << 16) / (6553600L)))) * (32768L /* 0.5 */)) >> 16)));
}

static void gtl_s_plasma(void)
{
    if ((gtl_plasma_started == 0)) {
        gba_blend_off();
        gba_mode7_off();
        gba_abg_off();
        gba_mode15();
        gtl_plasma_started = 1;
    }
    { int gtl_ph = (((gtl_t2) << 1) + (gtl_t2));
        { int gtl_y = 0;
            while ((gtl_y < 128)) {
                { int gtl_x = 0;
                    while ((gtl_x < 160)) {
                        { long gtl_r = (8388608L + (gba_fsin((long)((((long long)(((long)(gtl_x + gtl_ph) << 16))) << 16) / (2621440L))) * 127));
                            { long gtl_g = (8388608L + (gba_fsin((long)((((long long)(((long)(gtl_y - gtl_ph) << 16))) << 16) / (3276800L))) * 127));
                                { long gtl_b = (8388608L + (gba_fsin((long)((((long long)(((long)(gtl_x + gtl_y) << 16))) << 16) / (3932160L))) * 127));
                                    gba_fillrect15(gtl_x, gtl_y, 8, 8, gba_rgb15((int)(gtl_r >> 16), (int)(gtl_g >> 16), (int)(gtl_b >> 16)));
                                    gtl_x = (gtl_x + 8);
                                }
                            }
                        }
                    }
                    gtl_y = (gtl_y + 8);
                }
            }
            gba_flip15();
        }
    }
}

static void gtl_reset_display(void)
{
    gba_abg_off();
    gba_mode7_off();
    gba_blend_off();
}

int main(void)
{
    gba_init();
    gtl__init();
    for (;;) {
        gba_vsync();
        gtl__update60();
        gtl__draw();
        gba_endframe();
    }
    return 0;
}
