/* generated by gbalua from main.lua - edit the .lua, not this file */
#include "gba_api.h"

static void gtl__init(void);
static void gtl_fire(void);
static void gtl__update(void);
static void gtl__draw(void);

int gtl_px = 108;
int gtl_py = 130;
int gtl_pcool = 0;
int gtl_bx[8];
int gtl_by[8];
unsigned char gtl_ba[8];
int gtl_enx[12];
int gtl_eny[12];
unsigned char gtl_eal[12];
int gtl_edir = 1;
int gtl_edx = 0;
int gtl_alive = 12;
int gtl_score = 0;
int gtl_lives = 3;
int gtl_state = 0;
int gtl_scrolly = 0;
int gtl_fadet = 0;
int gtl_endt = 0;

static void gtl__init(void)
{
    gba_map_show(0);
    gba_music(0, 1);
    { unsigned char gtl_i = 1; unsigned char L_lim0 = 12;
        for (; gtl_i <= L_lim0; ++gtl_i) {
            { int gtl_col = (((gtl_i - 1)) % (6));
                { int gtl_row = (((gtl_i - 1)) / (6));
                    gtl_enx[gtl_i - 1] = (24 + (((gtl_col) << 5)));
                    gtl_eny[gtl_i - 1] = (20 + (((gtl_row) << 4) + ((gtl_row) << 3)));
                    (gtl_eal - 1)[gtl_i] = 1;
                }
            }
        }
    }
    { unsigned char gtl_i = 1; unsigned char L_lim1 = 8;
        for (; gtl_i <= L_lim1; ++gtl_i) {
            (gtl_ba - 1)[gtl_i] = 0;
        }
    }
}

static void gtl_fire(void)
{
    { unsigned char gtl_i = 1; unsigned char L_lim2 = 8;
        for (; gtl_i <= L_lim2; ++gtl_i) {
            if (((unsigned char)(gtl_ba - 1)[gtl_i] == (unsigned char)0)) {
                gtl_bx[gtl_i - 1] = (gtl_px + 4);
                gtl_by[gtl_i - 1] = gtl_py;
                (gtl_ba - 1)[gtl_i] = 1;
                gba_sfx(0, -1);
                return;
            }
        }
    }
}

static void gtl__update(void)
{
    if ((gtl_state != 0)) {
        if ((gtl_endt < 30)) {
            gtl_endt = (gtl_endt + 1);
        }
        gba_fade((long)(((long long)((long)((((long long)(((long)gtl_endt << 16))) << 16) / (1966080L))) * (45875L /* 0.7 */)) >> 16), 0);
        if (gba_btnp(4, 0)) {
            gba_run();
        }
        return;
    }
    if ((gtl_fadet < 30)) {
        gtl_fadet = (gtl_fadet + 1);
        gba_fade((65536L - (long)((((long long)(((long)gtl_fadet << 16))) << 16) / (1966080L))), 0);
    }
    gtl_scrolly = (gtl_scrolly + 1);
    gba_camera(0, ((-gtl_scrolly) >> 1));
    if (gba_btn(0, 0)) {
        gtl_px = (gtl_px - 3);
    }
    if (gba_btn(1, 0)) {
        gtl_px = (gtl_px + 3);
    }
    if ((gtl_px < 4)) {
        gtl_px = 4;
    }
    if ((gtl_px > 220)) {
        gtl_px = 220;
    }
    if ((gtl_pcool > 0)) {
        gtl_pcool = (gtl_pcool - 1);
    }
    if ((gba_btn(4, 0) && (gtl_pcool == 0))) {
        gtl_fire();
        gtl_pcool = 8;
    }
    { unsigned char gtl_i = 1; unsigned char L_lim3 = 8;
        for (; gtl_i <= L_lim3; ++gtl_i) {
            if (((unsigned char)(gtl_ba - 1)[gtl_i] != (unsigned char)0)) {
                gtl_by[gtl_i - 1] = ((gtl_by - 1)[gtl_i] - 6);
                if ((((gtl_by - 1)[gtl_i] - ((-8))) < 0)) {
                    (gtl_ba - 1)[gtl_i] = 0;
                }
            }
        }
    }
    gtl_edx = (gtl_edx + gtl_edir);
    if ((gtl_edx > 24)) {
        gtl_edir = (-1);
    }
    if (((gtl_edx - ((-24))) < 0)) {
        gtl_edir = 1;
    }
    { unsigned char gtl_e = 1; unsigned char L_lim4 = 12;
        for (; gtl_e <= L_lim4; ++gtl_e) {
            if (((unsigned char)(gtl_eal - 1)[gtl_e] != (unsigned char)0)) {
                { int gtl_ex = ((gtl_enx - 1)[gtl_e] + gtl_edx);
                    { int gtl_ey = ((gtl_eny - 1)[gtl_e] + (gtl_scrolly >> 3));
                        if ((gtl_ey > 120)) {
                            gtl_state = 2;
                            gba_music((-1), 1);
                            return;
                        }
                        { unsigned char gtl_i = 1; unsigned char L_lim5 = 8;
                            for (; gtl_i <= L_lim5; ++gtl_i) {
                                if (((unsigned char)(gtl_ba - 1)[gtl_i] != (unsigned char)0)) {
                                    { int gtl_dx = ((gtl_bx - 1)[gtl_i] - gtl_ex);
                                        { int gtl_dy = ((gtl_by - 1)[gtl_i] - gtl_ey);
                                            if ((((((gtl_dx - ((-12))) > 0) && (gtl_dx < 12)) && ((gtl_dy - ((-12))) > 0)) && (gtl_dy < 12))) {
                                                (gtl_eal - 1)[gtl_e] = 0;
                                                (gtl_ba - 1)[gtl_i] = 0;
                                                gtl_score = (gtl_score + 10);
                                                gtl_alive = (gtl_alive - 1);
                                                gba_sfx(0, -1);
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    if ((gtl_alive <= 0)) {
        gtl_state = 1;
        gba_music((-1), 1);
    }
}

static void gtl__draw(void)
{
    if ((gtl_state == 1)) {
        gba_print("YOU WIN!", 88, 60, 11);
        gba_print("score", 100, 80, 7);
        gba_print_int(gtl_score, 130, 80, 10);
        gba_print("press A", 96, 100, 12);
        return;
    }
    if ((gtl_state == 2)) {
        gba_print("GAME OVER", 84, 60, 8);
        gba_print("score", 100, 80, 7);
        gba_print_int(gtl_score, 130, 80, 10);
        gba_print("press A", 96, 100, 12);
        return;
    }
    gba_print("score", 4, 4, 7);
    gba_print_int(gtl_score, 44, 4, 10);
    gba_print("lives", 170, 4, 7);
    gba_print_int(gtl_lives, 210, 4, 8);
    gba_spr(0, gtl_px, gtl_py, 2, 2, 0 | (0 << 1));
    { unsigned char gtl_i = 1; unsigned char L_lim6 = 8;
        for (; gtl_i <= L_lim6; ++gtl_i) {
            if (((unsigned char)(gtl_ba - 1)[gtl_i] != (unsigned char)0)) {
                gba_spr8(2, (gtl_bx - 1)[gtl_i], (gtl_by - 1)[gtl_i], 0);
            }
        }
    }
    { unsigned char gtl_e = 1; unsigned char L_lim7 = 12;
        for (; gtl_e <= L_lim7; ++gtl_e) {
            if (((unsigned char)(gtl_eal - 1)[gtl_e] != (unsigned char)0)) {
                gba_spr(1, ((gtl_enx - 1)[gtl_e] + gtl_edx), ((gtl_eny - 1)[gtl_e] + (gtl_scrolly >> 3)), 2, 2, 0 | (0 << 1));
            }
        }
    }
}

int main(void)
{
    gba_init();
    gtl__init();
    for (;;) {
        gba_vsync();
        gtl__update();
        gtl__draw();
        gba_endframe();
    }
    return 0;
}
