/* generated by gbalua from main.lua - edit the .lua, not this file */
#include "gba_api.h"

static void gtl__init(void);
static void gtl__update(void);
static void gtl__draw(void);

int gtl_wx = 120;
int gtl_wy = 80;
int gtl_wr = 44;

static void gtl__init(void)
{
    gba_mode7();
    gba_mode7_cam(8388608L, 8388608L, 0L, 65536L);
}

static void gtl__update(void)
{
    if (gba_btn(0, 0)) {
        gtl_wx = (gtl_wx - 3);
    }
    if (gba_btn(1, 0)) {
        gtl_wx = (gtl_wx + 3);
    }
    if (gba_btn(2, 0)) {
        gtl_wy = (gtl_wy - 3);
    }
    if (gba_btn(3, 0)) {
        gtl_wy = (gtl_wy + 3);
    }
    if (((gtl_wx - (gtl_wr)) < 0)) {
        gtl_wx = gtl_wr;
    }
    if (((gtl_wx - ((240 - gtl_wr))) > 0)) {
        gtl_wx = (240 - gtl_wr);
    }
    if (((gtl_wy - (gtl_wr)) < 0)) {
        gtl_wy = gtl_wr;
    }
    if (((gtl_wy - ((160 - gtl_wr))) > 0)) {
        gtl_wy = (160 - gtl_wr);
    }
    if (gba_btn(4, 0)) {
        gtl_wr = (gtl_wr + 2);
    }
    if (gba_btn(5, 0)) {
        gtl_wr = (gtl_wr - 2);
    }
    if ((gtl_wr < 12)) {
        gtl_wr = 12;
    }
    if ((gtl_wr > 78)) {
        gtl_wr = 78;
    }
    if (gba_btn(6, 0)) {
        gba_window_off();
    } else {
        gba_window((gtl_wx - gtl_wr), (gtl_wy - gtl_wr), (gtl_wx + gtl_wr), (gtl_wy + gtl_wr));
    }
}

static void gtl__draw(void)
{
    gba_print("windows", 8, 8, 7);
}

int main(void)
{
    gba_init();
    gtl__init();
    for (;;) {
        gba_vsync();
        gtl__update();
        gtl__draw();
        gba_endframe();
    }
    return 0;
}
