/* generated by gbalua from main.lua - edit the .lua, not this file */
#include "gba_api.h"

static void lcl__init(void);
static void lcl__update(void);
static void lcl__draw(void);

int lcl_wx = 120;
int lcl_wy = 80;
int lcl_wr = 44;

static void lcl__init(void)
{
    gba_mode7();
    gba_mode7_cam(8388608L, 8388608L, 0L, 65536L);
}

static void lcl__update(void)
{
    if (gba_btn(0, 0)) {
        lcl_wx = (lcl_wx - 3);
    }
    if (gba_btn(1, 0)) {
        lcl_wx = (lcl_wx + 3);
    }
    if (gba_btn(2, 0)) {
        lcl_wy = (lcl_wy - 3);
    }
    if (gba_btn(3, 0)) {
        lcl_wy = (lcl_wy + 3);
    }
    if (((lcl_wx - (lcl_wr)) < 0)) {
        lcl_wx = lcl_wr;
    }
    if (((lcl_wx - ((240 - lcl_wr))) > 0)) {
        lcl_wx = (240 - lcl_wr);
    }
    if (((lcl_wy - (lcl_wr)) < 0)) {
        lcl_wy = lcl_wr;
    }
    if (((lcl_wy - ((160 - lcl_wr))) > 0)) {
        lcl_wy = (160 - lcl_wr);
    }
    if (gba_btn(4, 0)) {
        lcl_wr = (lcl_wr + 2);
    }
    if (gba_btn(5, 0)) {
        lcl_wr = (lcl_wr - 2);
    }
    if ((lcl_wr < 12)) {
        lcl_wr = 12;
    }
    if ((lcl_wr > 78)) {
        lcl_wr = 78;
    }
    if (gba_btn(6, 0)) {
        gba_window_off();
    } else {
        gba_window((lcl_wx - lcl_wr), (lcl_wy - lcl_wr), (lcl_wx + lcl_wr), (lcl_wy + lcl_wr));
    }
}

static void lcl__draw(void)
{
    gba_print("windows", 8, 8, 7);
}

int main(void)
{
    gba_init();
    lcl__init();
    for (;;) {
        gba_vsync();
        lcl__update();
        lcl__draw();
        gba_endframe();
    }
    return 0;
}
