/* generated by gbalua from synth-shapes.lua - edit the .lua, not this file */
#include "gba_api.h"

static void lcl__draw(void);

static void lcl__draw(void)
{
    gba_cls(1);
    gba_rectfill(4, 4, 20, 20, 8);
    gba_circfill(64, 64, 10, 10);
    gba_line(0, 0, 127, 127, 7);
    gba_spr(0, 10, 10, 1, 1, 0 | (0 << 1));
    gba_print("hi", 4, 4, 7);
}

int main(void)
{
    gba_init();
    for (;;) {
        gba_vsync();
        lcl__draw();
        gba_endframe();
    }
    return 0;
}
