/* generated by gbalua from synth-array.lua - edit the .lua, not this file */
#include "gba_api.h"

static void lcl__update(void);
static void lcl__draw(void);

int lcl_a[16];
unsigned char lcl_b[8];

static void lcl__update(void)
{
    lcl_a[0] = 5;
    lcl_b[0] = 2;
}

static void lcl__draw(void)
{
}

int main(void)
{
    gba_init();
    for (;;) {
        gba_vsync();
        lcl__update();
        lcl__draw();
        gba_endframe();
    }
    return 0;
}
