/* generated by gbalua from synth-fixedmath.lua - edit the .lua, not this file */
#include "gba_api.h"

static void gtl__update(void);
static void gtl__draw(void);

long gtl_x = 0L; /* 0 */

static void gtl__update(void)
{
    gtl_x = (gtl_x + 32768L /* 0.5 */);
    gtl_x = ((gtl_x) + ((gtl_x) >> 1));
    gtl_x = (long)((((long long)(gtl_x)) << 16) / (196608L));
}

static void gtl__draw(void)
{
}

int main(void)
{
    gba_init();
    for (;;) {
        gba_vsync();
        gtl__update();
        gtl__draw();
        gba_endframe();
    }
    return 0;
}
