/* generated by gbalua from synth-btn.lua - edit the .lua, not this file */
#include "gba_api.h"

static void gtl__update(void);
static void gtl__draw(void);

static void gtl__update(void)
{
    if (gba_btn(0, 0)) {
    }
    if (gba_btnp(4, 0)) {
    }
}

static void gtl__draw(void)
{
}

int main(void)
{
    gba_init();
    for (;;) {
        gba_vsync();
        gtl__update();
        gtl__draw();
        gba_endframe();
    }
    return 0;
}
