/* generated by gbalua from synth-func.lua - edit the .lua, not this file */
#include "gba_api.h"

static int gtl_helper(void);
static void gtl__update(void);
static void gtl__draw(void);

static int gtl_helper(void)
{
    return (gt_p0 + gt_p1);
}

static void gtl__update(void)
{
    { int gtl_z = (((1) + (2)));
    }
}

static void gtl__draw(void)
{
}

int main(void)
{
    gba_init();
    for (;;) {
        gba_vsync();
        gtl__update();
        gtl__draw();
        gba_endframe();
    }
    return 0;
}
