/* generated by gbalua from synth-func.lua - edit the .lua, not this file */
#include "gba_api.h"

static int lcl_helper(void);
static void lcl__update(void);
static void lcl__draw(void);

static int lcl_helper(void)
{
    return (lc_p0 + lc_p1);
}

static void lcl__update(void)
{
    { int lcl_z = (((1) + (2)));
    }
}

static void lcl__draw(void)
{
}

int main(void)
{
    gba_init();
    for (;;) {
        gba_vsync();
        lcl__update();
        lcl__draw();
        gba_endframe();
    }
    return 0;
}
