/* generated by gbalua from synth-minmax.lua - edit the .lua, not this file */
#include "gba_api.h"

static void lcl__update(void);
static void lcl__draw(void);

static void lcl__update(void)
{
    { int lcl_a = (((unsigned char)1 < (unsigned char)2) ? (1) : (2));
        { int lcl_b = (((unsigned char)3 > (unsigned char)4) ? (3) : (4));
            { int lcl_c = (((unsigned char)1 < (unsigned char)2) ? (((unsigned char)2 < (unsigned char)3) ? (2) : (((unsigned char)1 < (unsigned char)3) ? (3) : (1))) : (((unsigned char)1 < (unsigned char)3) ? (1) : (((unsigned char)2 < (unsigned char)3) ? (3) : (2))));
                { int lcl_d = lc_absi((-5));
                }
            }
        }
    }
}

static void lcl__draw(void)
{
}

int main(void)
{
    gba_init();
    for (;;) {
        gba_vsync();
        lcl__update();
        lcl__draw();
        gba_endframe();
    }
    return 0;
}
