/* generated by gbalua from synth-fornum.lua - edit the .lua, not this file */
#include "gba_api.h"

static void lcl__update(void);
static void lcl__draw(void);

static void lcl__update(void)
{
    { int lcl_i = 0; int L_lim0 = 255;
        for (; lcl_i <= L_lim0; ++lcl_i) {
        }
    }
    { int lcl_j = 1; int L_lim1 = 10;
        for (; lcl_j <= L_lim1; lcl_j += 2) {
        }
    }
}

static void lcl__draw(void)
{
}

int main(void)
{
    gba_init();
    for (;;) {
        gba_vsync();
        lcl__update();
        lcl__draw();
        gba_endframe();
    }
    return 0;
}
