/* generated by gbalua from synth-fornum.lua - edit the .lua, not this file */
#include "gba_api.h"

static void gtl__update(void);
static void gtl__draw(void);

static void gtl__update(void)
{
    { int gtl_i = 0; int L_lim0 = 255;
        for (; gtl_i <= L_lim0; ++gtl_i) {
        }
    }
    { int gtl_j = 1; int L_lim1 = 10;
        for (; gtl_j <= L_lim1; gtl_j += 2) {
        }
    }
}

static void gtl__draw(void)
{
}

int main(void)
{
    gba_init();
    for (;;) {
        gba_vsync();
        gtl__update();
        gtl__draw();
        gba_endframe();
    }
    return 0;
}
