/* generated by gbalua from synth-fixedmath.lua - edit the .lua, not this file */
#include "gba_api.h"

static void lcl__update(void);
static void lcl__draw(void);

long lcl_x = 0L; /* 0 */

static void lcl__update(void)
{
    lcl_x = (lcl_x + 32768L /* 0.5 */);
    lcl_x = ((lcl_x) + ((lcl_x) >> 1));
    lcl_x = (long)((((long long)(lcl_x)) << 16) / (196608L));
}

static void lcl__draw(void)
{
}

int main(void)
{
    gba_init();
    for (;;) {
        gba_vsync();
        lcl__update();
        lcl__draw();
        gba_endframe();
    }
    return 0;
}
