/* generated by gbalua from synth-btn.lua - edit the .lua, not this file */
#include "gba_api.h"

static void lcl__update(void);
static void lcl__draw(void);

static void lcl__update(void)
{
    if (gba_btn(0, 0)) {
    }
    if (gba_btnp(4, 0)) {
    }
}

static void lcl__draw(void)
{
}

int main(void)
{
    gba_init();
    for (;;) {
        gba_vsync();
        lcl__update();
        lcl__draw();
        gba_endframe();
    }
    return 0;
}
