/* generated by gbalua from synth-array.lua - edit the .lua, not this file */
#include "gba_api.h"

static void gtl__update(void);
static void gtl__draw(void);

int gtl_a[16];
unsigned char gtl_b[8];

static void gtl__update(void)
{
    gtl_a[0] = 5;
    gtl_b[0] = 2;
}

static void gtl__draw(void)
{
}

int main(void)
{
    gba_init();
    for (;;) {
        gba_vsync();
        gtl__update();
        gtl__draw();
        gba_endframe();
    }
    return 0;
}
